services:
  site:
    build: .
    image: ghcr.io/wanderleimarques2108-web/projeto-devops:latest
    container_name: site
    restart: unless-stopped
    ports:
      - "80:80"

  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - kuma_data:/app/data

volumes:
  kuma_data:
